- hosts: bastion
  pre_tasks:
    - wait_for:
        host: "{{ hostvars[nxos]['ansible_host'] }}"
        port: "{{ test_port }}"
  roles:
    - prepare-workspace
    - run-network-integration-tests
