- hosts: bastion
  roles:
    - prepare-workspace
  tasks:
    - name: Start zuul console daemon
      zuul_console:
    - name: Create inventory for openvswitch node
      copy:
        content: |
          [openvswitch]
          "{{ hostvars['openvswitch']['ansible_host'] }}" ansible_connection=local
        dest: /tmp/inventory

    - shell: pip install -r requirements.txt && source hacking/env-setup && ansible-test network-integration openvswitch_.* --inventory /tmp/inventory -vvv
      args:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
