- hosts: localhost
  connection: local

  tasks:
    - name: Synchronize src repos to workspace directory.
      synchronize:
        dest: "{{ zuul_workspace_root }}"
        src: "{{ zuul.executor.src_root }}"

- hosts: bastion
  tasks:
    - shell: source hacking/env-setup && ansible-test network-integration openvswitch-.* -vvv
      args:
        executable: /bin/bash
