- hosts: bastion
  tasks:
    - name: Synchronize src repos to workspace directory.
      synchronize:
        dest: .
        src: "{{ zuul.executor.src_root }}"
    - name: Create inventory for openvswitch node
      copy:
        content: |
          [openvswitch]
          "{{ hostvars['openvswitch']['ansible_host'] }}" ansible_connection=local
        dest: /tmp/inventory

    - shell: "pip install -r {{ zuul.project_src_dir }}/requirements.txt"
    - shell: source hacking/env-setup && ansible-test network-integration openvswitch_.* --inventory /tmp/inventory -vvv
      args:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
