- hosts: bastion
  tasks:
    - name: Synchronize src repos to workspace directory.
      synchronize:
        dest: .
        src: "{{ zuul.executor.src_root }}"

    - shell: source hacking/env-setup && ansible-test network-integration openvswitch-.* -vvv
      args:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
